FROM python:3.12

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip && pip install poetry==1.8.3
RUN apt-get install ffmpeg

COPY poetry.lock pyproject.toml ./

COPY . .

RUN poetry lock
RUN poetry self add poetry-dotenv-plugin
RUN poetry install

EXPOSE 8000

CMD ["poetry", "run", "python", "./App/main.py"]
