FROM python:3.12

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip && pip install poetry==1.8.3

COPY poetry.lock pyproject.toml ./

COPY pyproject.toml .
COPY poetry.lock .

RUN poetry lock
RUN poetry self add poetry-dotenv-plugin
RUN poetry install

COPY . .

EXPOSE 8500

CMD ["poetry", "run", "python", "./App/Bot/main.py"]